### PR TITLE
Fix back

### LINKED ISSUE #31: Unexpected navigation results
Getting unexpected results with more/back button as well as navigation patterns on both iOS and Android

Examples:
Home -> Services -> Behavioral Health -> Autumn St. 
- tapping back button takes you to Locations view (?) instead of back through view history
- tapping back button at this point removes back button and nothing happens 

Home -> Locations -> Ashtabula Cty -> Andover Primary Care
- back button works OK until you get to Locations view, then it goes away (can't go back to Home view)
- if I tap on Home and then from Home view click on Locations it takes me to Andover Primary Care location details page instead of Locations default view. If I tap on Locations tab, same thing, Andover Primary Care Locations Detail page. I can't navigate to Locations default view. This pattern happens with Services and Providers as well.
In other words, if I go to a Location detail view, tap on Home, then tap on Locations, I am taken to the Location detail view instead of Location default view.

On iOS, if I use the More button to get to Services view then tap back button it takes me to More view but I can't go back any further since back button is removed on this view.

### PR DESCRIPTION
**Pull request by elimin8r**
Fixes #31

### CODE REVIEW

**Comment by elimin8r** [comment]
I added another commit to this branch. i think that addresses some of the issues.

basically whats going on is that there is two types of navigation going on: Tabs, and Details within the Tab.

The back button has no clue about the tabs so if it goes back, it might not change the tab.

If you want to think about a redesign, like maybe moving the back button out of the actionbar and into the actual pages, it might be more of what you are trying to achieve.

**Comment by elimin8r** [comment]
@dbay920 I added some commits with unstyled back buttons on the pages that needed it. let me know what you think.

**Comment by elimin8r** [comment]
i added a fix for that. try it now.

**Comment by dbay920** [comment]
App opens now on android but throws exception when I tap on home page buttons:

TypeError: Cannot set property 'selectedIndex' of undefined
File: "file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js, line: 229, column: 40

StackTrace: 
	Frame: function:'ItemsComponent.setSelectedIndex', file:'file:///data/data/org.nativescript.MyPHN/files/app/items.component.js', line: 26, column: 48
	Frame: function:'HomeComponent.goToUrl', file:'file:///data/data/org.nativescript.MyPHN/files/app/home/home.component.js', line: 21, column: 42
	Frame: function:'', file:'', line: 47, column: 24
	Frame: function:'handleEvent', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 11805, column: 138
	Frame: function:'callWithDebugContext', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13013, column: 42
	Frame: function:'debugHandleEvent', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12601, column: 12
	Frame: function:'dispatchEvent', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 8780, column: 21
	Frame: function:'', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9370, column: 38
	Frame: function:'', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/nativescript-angular/renderer.js', line: 173, column: 26
	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26
	Frame: function:'onInvoke', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4132, column: 37
	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 364, column: 32
	Frame: function:'Zone.run', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 125, column: 43
	Frame: function:'NgZone.run', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 4001, column: 62
	Frame: function:'zonedCallback', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/nativescript-angular/renderer.js', line: 172, column: 24
	Frame: function:'_executeCallback', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js', line: 283, column: 27
	Frame: function:'TapAndDoubleTapGestureListenerImpl.onSingleTapUp', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js', line: 25, column: 17
	Frame: function:'GesturesObserver.androidOnTouchEvent', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/tns-core-modules/ui/gestures/gestures.js', line: 229, column: 41
	Frame: function:'', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 34, column: 29
	Frame: function:'TouchListenerImpl.onTouch', file:'file:///data/data/org.nativescript.MyPHN/files/app/tns_modules/tns-core-modules/ui/core/view/view.js', line: 33, column: 22


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
	at com.tns.Runtime.callJSMethod(Runtime.java:953)
	at com.tns.Runtime.callJSMethod(Runtime.java:937)
	at com.tns.Runtime.callJSMethod(Runtime.java:929)
	at com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__TouchListenerImpl.onTouch(Object_frnal_ts_helpers_l58_c38__TouchListenerImpl.java:13)
	at android.view.View.dispatchTouchEvent(View.java:10775)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6420)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:607)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3240)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:569)
	at android.view.View.dispatchPointerEvent(View.java:11008)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5162)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5014)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4691)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4748)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4592)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4558)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4566)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7098)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7030)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6991)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by elimin8r** [comment]
try it now

**Comment by elimin8r** [comment]
@dbay920 Did this address #34?

**Pull request merged**
