### PR TITLE
feat(items): reset tabs when going home

### LINKED ISSUE #35: Reset tabs on home
Home tab will reset other tabbed views on tap

### PR DESCRIPTION
**Pull request by elimin8r**
fixes #35

### CODE REVIEW

**Comment by dbay920** [comment]
Also noticing on iOS and Android:
From Home, when you tap on Providers then tap on a category, it goes to Services landing page

**Comment by elimin8r** [comment]
its now pulling the data from the link you gave me. see the email about the data being bad.

**Comment by dbay920** [comment]
Still getting crash on load of locations by county, now happens for all counties, not just a few. This is true for both iOS and Android tests using emulators and real devices. Please run emulators on your end and let me know if it is crashing for you as well.

Thanks,

David Bayley
Web Development/Marketing Specialist
Corporate & Community Relations
63 Pitt Street
Sharon, PA 16146
(724) 342-3002 Ext. 1545


[cid:image001.png@01CFCB67.2DC307E0]

**Comment by dbay920** [comment]
Looks like we’re getting close, removed comments and all counties working except for Mercer…

David Bayley
Web Development/Marketing Specialist
Corporate & Community Relations
63 Pitt Street
Sharon, PA 16146
(724) 342-3002 Ext. 1545


[cid:image001.png@01CFCB67.2DC307E0]

**Comment by dbay920** [comment]
Removed a pharmacy from the website backend that wasn’t in json, now all counties are working!


David Bayley
Web Development/Marketing Specialist
Corporate & Community Relations
63 Pitt Street
Sharon, PA 16146
(724) 342-3002 Ext. 1545


[cid:image001.png@01CFCB67.2DC307E0]

**Comment by elimin8r** [comment]
yay. good data goes a long way

**Comment by elimin8r** [comment]
im going to merge this since it contains a fix that is blocking development on #24

**Pull request merged**
