### PR TITLE
Provider to native

### PR DESCRIPTION
**Pull request by elimin8r**

### CODE REVIEW

**Comment by elimin8r** [comment]
Im wondering if there might be some old files lying around cause i had that
problem when i was working through it.

Try deleting locations.service.js and rebuilding. If that doesnt work try
to reclone it.

Thats weird that this is happening more often now.

**Comment by dbay920** [comment]
Re-cloned, made sure to check out branch first, ran build, still getting  errors where data is not loading

David Bayley
Web Development/Marketing Specialist
Corporate & Community Relations
63 Pitt Street
Sharon, PA 16146
(724) 342-3002 Ext. 1545


[cid:image001.png@01CFCB67.2DC307E0]

**Comment by elimin8r** [comment]
are u testing on device or emulator?

**Comment by dbay920** [comment]
Device for both platforms. Deleted app, reset phone’s settings

David Bayley
Web Development/Marketing Specialist
Corporate & Community Relations
63 Pitt Street
Sharon, PA 16146
(724) 342-3002 Ext. 1545


[cid:image001.png@01CFCB67.2DC307E0]

**Pull request merged**
